[package]
name = "read_file_into_data"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data_struct={path="../../data_struct"}
csv="*"